export const CATEGORIES = {
		
		NOT_SELECTED:		-1,
		MISCELLANEOUS: 		0,
		ROOTS:				1,
		POTATOES:			2,
		FRUITS:				3,
		VEGETABLES:			4,
		BERRIES:			5,
		MUSHROOMS:			6,
		CHICKEN:			7,
		FISH:				8,
		CRAYFISH:			9,
		MEAT:				10,
		SAUSAGES:			11,		
		MILK: 				12,
		CHEESE: 			13,
		ICE_CREAM: 			14,
		WATERS:				15,
		TABLE_SPREADS:		16,
		OLIVE_OIL:			17,
		JELLY:				18,
		JUICE:				19,		
		SUGAR:				20,		
		HONEY:				21,
		CANDY:				22,
		COFFEE_EXTRACTS:	23,
		COFFEE:				24,
		TEA:				25,
		CHOCOLATE:			26,
		SUPPLEMENTS:		27,
		ALCOHOL:			28,
		LOW_LACTOSE:		29,
		LACTOSE_FREE:		30,
		GLUTEN_FREE:		31,
		LOW_GLUTEN:			32,
		SPORT_PRODUCTS:		33,
		INSECTS:			34,
		ENERGY_DRINKS:		35
		
};